package EHRAppointment;

import EHRAppointment.mainWindow;
import EHRAppointment.Patient;
import java.awt.Dimension;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import org.hibernate.Session;

/**
 *
 * @author Austin, Olena, Daniel
 */
public class DemographicInterface extends javax.swing.JFrame {
    private static final long serialVersionUID = -7189837937142270390L;

    /**
     * Creates new form Demographics
     */
    Session session;
    Patient patient;
    boolean toggle = false;                 //To toggle between edit mode
    boolean newPatient = false;             //Same interface is used to add new patient. Check this is new patient or not
    SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd"); //To check the format of entered date
    mainWindow main;

    public DemographicInterface(Session session, Patient patient,mainWindow main) {
        this.session = session;
        this.patient = patient;
        this.main=main;
        initComponents();
        if (patient != null) {      //If not a new patient update the data
            updateData();
        }
        showHideEdit(toggle);       //Initially hiding editing 
        jButton1.setEnabled(toggle);
    }

    public DemographicInterface(Session session, Patient patient, boolean newPatient,mainWindow main) {
        this.session = session;
        this.patient = patient;
        this.toggle = newPatient;
        this.newPatient = newPatient;
        this.main=main;
        
        initComponents();
        if (patient != null) {  //If not a new patient update the data
            clearData();
        }
        if(newPatient){
            jToggleButton1.setVisible(false);   //If adding a patient remove edit button
            jButton1.setText(" Add ");          //If new patient is adding change name of updat into add
        }
        showHideEdit(toggle);
        jButton1.setEnabled(toggle);
    }

    @Override
    public Dimension preferredSize() {
        return super.preferredSize(); //To change body of generated methods, choose Tools | Templates.
    }

    private void updateData() {             //Updating demographic information of the patient
        this.PatientIDData.setText(patient.getPatientId() + "");
        this.NameData.setText(patient.getName());
        this.BirthdayData.setText(patient.getBirthday().toString());
        this.SexData.setText(patient.getSex());
        this.MaritalStatusData.setText(patient.getMaritalStatus());
        this.JobData.setText(patient.getJob());
        this.PhoneData.setText(patient.getPhone());
        this.jTextArea1.setText(patient.getAddress());
    }

    private void clearData() {      //Remove the data

        this.PatientIDData.setText("");
        this.NameData.setText("");
        this.BirthdayData.setText("");
        this.SexData.setText("");
        this.MaritalStatusData.setText("");
        this.JobData.setText("");
        this.PhoneData.setText("");
        this.jTextArea1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        PatientInformation = new javax.swing.JLabel();
        PatientID = new javax.swing.JLabel();
        PatientIDData = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        NameData = new javax.swing.JLabel();
        Birthday = new javax.swing.JLabel();
        BirthdayData = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        SexData = new javax.swing.JLabel();
        MaritalStatus = new javax.swing.JLabel();
        MaritalStatusData = new javax.swing.JLabel();
        Job = new javax.swing.JLabel();
        JobData = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        PhoneData = new javax.swing.JLabel();
        Adress = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setTitle("Patient Demographic Information");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon_transparent.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PatientInformation.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        PatientInformation.setText("Patient Information");
        jPanel1.add(PatientInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        PatientID.setText("Patient ID:");
        jPanel1.add(PatientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        PatientIDData.setText("none");
        jPanel1.add(PatientIDData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, 20));

        Name.setText("Name:");
        jPanel1.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        NameData.setText("none");
        jPanel1.add(NameData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        Birthday.setText("Birthday:");
        jPanel1.add(Birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        BirthdayData.setText("none");
        jPanel1.add(BirthdayData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        Sex.setText("Sex:");
        jPanel1.add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        SexData.setText("none");
        jPanel1.add(SexData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));

        MaritalStatus.setText("Marital Status:");
        jPanel1.add(MaritalStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        MaritalStatusData.setText("none");
        jPanel1.add(MaritalStatusData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        Job.setText("Job:");
        jPanel1.add(Job, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        JobData.setText("none");
        jPanel1.add(JobData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        Phone.setText("Phone:");
        jPanel1.add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        PhoneData.setText("none");
        jPanel1.add(PhoneData, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, -1, -1));

        Adress.setText("Address:");
        jPanel1.add(Adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jToggleButton1.setBackground(new java.awt.Color(204, 204, 255));
        jToggleButton1.setText("Edit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 81, -1));

        jTextField2.setText(" ");
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 110, -1));

        jTextField3.setText(" ");
        jTextField3.setToolTipText("yyyy-mm-dd");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 110, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "male", "female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 110, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "single", "married", "devorced" }));
        jPanel1.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, -1));

        jTextField4.setText(" ");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 110, -1));

        jTextField5.setText(" ");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 110, -1));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, 81, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 170, 81, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient icon.jpg"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 100, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        //To get toggeling action change the variable
        if (toggle) {
            toggle = false;
            this.showHideEdit(toggle);
            jButton1.setEnabled(toggle);
        } else {
            toggle = true;
            this.showHideEdit(toggle);
            jButton1.setEnabled(toggle);
        }


    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            java.sql.Date sqlDate = null;
            java.util.Date invoiceDate = formatDate.parse(jTextField3.getText());   //Checking the date format
            sqlDate = new java.sql.Date(invoiceDate.getTime());

            patient.setName(jTextField2.getText());                   // Setting data object 
            patient.setBirthday(sqlDate);
            patient.setSex(jComboBox1.getSelectedItem().toString());
            patient.setMaritalStatus(jComboBox2.getSelectedItem().toString());
            patient.setJob(jTextField4.getText());
            patient.setPhone(jTextField5.getText());
            patient.setAddress(jTextArea1.getText());

            session.beginTransaction();
            if (newPatient) {               //If this is a new patient save if old patient update
                session.save(patient);
                main.currentPatient=patient;
            } else {
                session.update(patient);
            }
            session.getTransaction().commit();
            main.updateAllInterfaces();
            
            JOptionPane.showMessageDialog(null, "Update Successfull", "Update", JOptionPane.INFORMATION_MESSAGE);

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please enter date in correct format(yyyy-MM-dd)", "ALERT", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void showHideEdit(boolean b) {  //Showing and hiding edit data
        System.out.println(b);
        jComboBox1.setVisible(b);
        jComboBox2.setVisible(b);
        jTextField2.setVisible(b);
        jTextField3.setVisible(b);
        jTextField4.setVisible(b);
        jTextField5.setVisible(b);
        jTextArea1.setEditable(b);

        jTextField2.setText(NameData.getText());
        jTextField3.setText(BirthdayData.getText());
        jTextField4.setText(JobData.getText());
        jTextField5.setText(PhoneData.getText());
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DemographicInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Session s = null;
                Patient p = null;
                mainWindow m =null;
                new DemographicInterface(s, p,m).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Adress;
    private javax.swing.JLabel Birthday;
    private javax.swing.JLabel BirthdayData;
    private javax.swing.JLabel Job;
    private javax.swing.JLabel JobData;
    private javax.swing.JLabel MaritalStatus;
    private javax.swing.JLabel MaritalStatusData;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel NameData;
    private javax.swing.JLabel PatientID;
    private javax.swing.JLabel PatientIDData;
    private javax.swing.JLabel PatientInformation;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel PhoneData;
    private javax.swing.JLabel Sex;
    private javax.swing.JLabel SexData;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
