package EHRAppointment;


import EHRAppointment.mainWindow;
import EHRAppointment.Patient;
import java.util.Calendar;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Austin, Olena, Daniel
 */
public class PatientInfoInterface extends javax.swing.JPanel {
    private static final long serialVersionUID = -3353682820949357923L;

    /**
     * Creates new form PatientInfo
     */
    Session session;
    Patient patient;
    Insurance insurance;
    mainWindow main;

    /**
     *
     * @param session
     * @param main
     */
    public PatientInfoInterface(Session session,mainWindow main) {
        this.session = session;
        initComponents();
        this.main=main;

    }

    /**
     *
     * @param patient
     */
    public void updateInfo(Patient patient) {       //This will update the all other sub types of data 
        this.patient = patient;
        updateDemographic();
        updateInsuarence();
        updateMedicalInfo();
        updateVitals();
    }

    private void updateDemographic() {              //Update demographic information 
        Calendar today = Calendar.getInstance();    //To get age
        Calendar birthDate = Calendar.getInstance();
        birthDate.setTime(patient.getBirthday());
        int age = today.get(Calendar.YEAR) - birthDate.get(Calendar.YEAR);  //Calculate age
        this.jLabel13.setText(age+"");
        this.jLabel1.setText(patient.getName());
        
        this.jLabel28.setText(patient.getBirthday().toString());
        this.jLabel30.setText(patient.getSex());
        this.jLabel32.setText(patient.getMaritalStatus());
        this.jLabel34.setText(patient.getJob());
        this.ContactsData.setText(patient.getPhone());
    }

    /**
     *
     */
    public void updateInsuarence() {        //It is required to update in insuarence interface when values are changed

        session.beginTransaction();
        Query qr = session.createQuery("from Insurance where patientId =:code");
        qr.setParameter("code", patient.getPatientId());
        List<Insurance> result = qr.list();
        session.getTransaction().commit();

        if (result.isEmpty()) {
            //this.jButton2.setEnabled(false);
        } else {
            this.insurance = result.get(0);
            this.PhoneData.setText(insurance.getProvider());
            this.ProviderData.setText(insurance.getPlanName());
            this.PlanNameData.setText(insurance.getPolicyNumber());
        }

    }
    
    private void updateMedicalInfo(){   //Update medical info
        session.beginTransaction();
        Query qr = session.createQuery("from GeneralMedicalInfo where patientId =:code");
        qr.setParameter("code", patient.getPatientId());
        List<GeneralMedicalInfo> result = qr.list();
        session.getTransaction().commit();
        
        if(!result.isEmpty()){
            GeneralMedicalInfo medical = result.get(0);
            this.jLabel23.setText(medical.getMainMedicalProblem());
            this.jTextArea1.setText(medical.getMedicalProblems());
            this.jTextArea2.setText(medical.getAllergies());
        }else{
            this.jLabel23.setText("none");
            this.jTextArea1.setText("");
            this.jTextArea2.setText("");
        }
    }
    
    private void updateVitals(){
        
        session.beginTransaction(); 
        Query qr = session.createQuery("from Vitals where patientId =:code order by dateTime DESC");
        qr.setParameter("code", patient.getPatientId());
        List<Vitals> result = qr.list();
        session.getTransaction().commit();
        
        if(!result.isEmpty()){  //Check there are previous vitals are available
            Vitals vitals = result.get(0);
            
            jLabel3.setText(vitals.getDateTime().toString());
            jLabel5.setText(vitals.getBpSystolic()+"");
            jLabel7.setText(vitals.getBpDiastolic()+"");
            jLabel9.setText(vitals.getTemperature()+"");
            jLabel11.setText(vitals.getBmi()+"");
            jLabel15.setText(vitals.getWeight()+"");
            jLabel17.setText(vitals.getOxygenSaturation()+"");
            jLabel19.setText(vitals.getPulse()+"");
            jLabel21.setText(vitals.getHeight()+"");
        }else{
            jLabel3.setText("value");
            jLabel5.setText("value");
            jLabel7.setText("value");
            jLabel9.setText("value");
            jLabel11.setText("value");
            jLabel15.setText("value");
            jLabel17.setText("value");
            jLabel19.setText("value");
            jLabel21.setText("value");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
<<<<<<< HEAD
        MostRecentVisitVitals = new javax.swing.JLabel();
        BloodPressureSystolic = new javax.swing.JLabel();
        BloodPressureDiastolic = new javax.swing.JLabel();
        TemperatureC = new javax.swing.JLabel();
        BMI = new javax.swing.JLabel();
=======
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
>>>>>>> origin/master
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator2 = new javax.swing.JSeparator();
        Demographics = new javax.swing.JLabel();
        Birthday = new javax.swing.JLabel();
        Sex = new javax.swing.JLabel();
        MaritalStatus = new javax.swing.JLabel();
        Job = new javax.swing.JLabel();
        Contacts = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Provider = new javax.swing.JLabel();
        PlanName = new javax.swing.JLabel();
        PolicyNumber = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
<<<<<<< HEAD
        ContactsData = new javax.swing.JLabel();
        PhoneData = new javax.swing.JLabel();
        ProviderData = new javax.swing.JLabel();
        PlanNameData = new javax.swing.JLabel();
        PolicyNumberData = new javax.swing.JLabel();
        BloodPressureSystolicData = new javax.swing.JLabel();
        BloodPressureDiastolicData = new javax.swing.JLabel();
        TemperatureData = new javax.swing.JLabel();
        BMIData = new javax.swing.JLabel();
        WeightData = new javax.swing.JLabel();
        OxygenSaturationData = new javax.swing.JLabel();
        PulseData = new javax.swing.JLabel();
        HeightData = new javax.swing.JLabel();
=======
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
>>>>>>> origin/master

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Most recent visit vitals: ");

        jLabel3.setText("jLabel3");

        jLabel4.setText("Blood pressure systolic:");

        BloodPressureDiastolic.setText("Blood pressure diastolic:");

        jLabel8.setText("Temperature(C):");

        jLabel10.setText("BMI:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Age:");

        jLabel14.setText("Weight:");

        jLabel16.setText("Oxygen saturation:");

        jLabel18.setText("Pulse:");

        jLabel20.setText("Height:");

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel22.setText("Medical issue:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText(" Medical problems:");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Allergies:");

        jTextArea2.setEditable(false);
        jTextArea2.setBackground(new java.awt.Color(204, 204, 204));
        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        Demographics.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Demographics.setText("Demographics:");

        Birthday.setText("Birthday:");

        Sex.setText("Sex:");

        MaritalStatus.setText("Marital status:");

        Job.setText("Job:");

        Contacts.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Contacts.setText("Contacts:");

        Phone.setText("Phone:");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("More");
        jButton1.setToolTipText("View and edit demographic information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("Insurance:");

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setText("More");
        jButton2.setToolTipText("View and edit insurance info");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Provider.setText("Provider:");

        PlanName.setText("Plan name:");

        PolicyNumber.setText("Policy number:");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel45.setText("Patient Information");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient icon.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel5.setText("jLabel5");

        jLabel7.setText("jLabel7");

<<<<<<< HEAD
        ContactsData.setText("jLabel37");

        PhoneData.setText("jLabel40");

        ProviderData.setText("jLabel42");

        PlanNameData.setText("jLabel44");

        PolicyNumberData.setText("jLabel46");
=======
        jLabel9.setText("jLabel9");

        jLabel11.setText("jLabel11");

        jLabel13.setText("jLabel13");

        jLabel15.setText("jLabel15");

        jLabel17.setText("jLabel17");
>>>>>>> origin/master

        jLabel19.setText("jLabel19");

        jLabel21.setText("jLabel21");

        jLabel23.setText("jLabel23");

        jLabel28.setText("jLabel28");

        jLabel30.setText("jLabel30");

        jLabel32.setText("jLabel32");

        jLabel34.setText("jLabel34");

        jLabel37.setText("jLabel37");

        jLabel40.setText("jLabel40");

        jLabel42.setText("jLabel42");

        jLabel44.setText("jLabel44");

        jLabel46.setText("jLabel46");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel45)
                                .addGap(211, 211, 211)
                                .addComponent(jLabel12)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel22)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Demographics)
                            .addComponent(Birthday)
                            .addComponent(Sex)
                            .addComponent(MaritalStatus)
                            .addComponent(Job))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel32)
                            .addComponent(jLabel30)
                            .addComponent(jLabel28)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Contacts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContactsData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Phone)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PhoneData)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PolicyNumber)
                                .addGap(18, 18, 18)
                                .addComponent(PolicyNumberData))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(PlanName)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(PlanNameData))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(Provider)
                                    .addGap(49, 49, 49)
                                    .addComponent(ProviderData))))
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel15))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(126, 126, 126)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel20))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                                    .addComponent(MostRecentVisitVitals)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BloodPressureDiastolic)
                                            .addComponent(TemperatureC)
                                            .addComponent(BMI)
                                            .addComponent(Weight)
                                            .addComponent(OxygenSaturation)
                                            .addComponent(BloodPressureSystolic))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BloodPressureSystolicData)
                                            .addComponent(OxygenSaturationData)
                                            .addComponent(WeightData)
                                            .addComponent(BMIData)
                                            .addComponent(TemperatureData)
                                            .addComponent(BloodPressureDiastolicData)
                                            .addComponent(PulseData)
                                            .addComponent(HeightData))))
                                .addGap(61, 61, 61)))
=======
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(66, 66, 66)
>>>>>>> origin/master
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel45)
                            .addComponent(jLabel12)
                            .addComponent(jLabel22))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel3)
                    .addComponent(jLabel21)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
<<<<<<< HEAD
                            .addComponent(BloodPressureDiastolic)
                            .addComponent(BloodPressureDiastolicData))
=======
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
>>>>>>> origin/master
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
<<<<<<< HEAD
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Height)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Demographics)
                            .addComponent(Contacts)
                            .addComponent(jButton1)
                            .addComponent(jLabel38)
                            .addComponent(jButton2)
                            .addComponent(ContactsData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Birthday)
                            .addComponent(Phone)
                            .addComponent(Provider)
                            .addComponent(PhoneData)
                            .addComponent(ProviderData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Sex)
                            .addComponent(PlanName)
                            .addComponent(PlanNameData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MaritalStatus)
                            .addComponent(PolicyNumber)
                            .addComponent(PolicyNumberData))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Job))
                    .addComponent(HeightData))
                .addContainerGap(50, Short.MAX_VALUE))
=======
                    .addComponent(jLabel20)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel35)
                    .addComponent(jButton1)
                    .addComponent(jLabel38)
                    .addComponent(jButton2)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel36)
                    .addComponent(jLabel39)
                    .addComponent(jLabel28)
                    .addComponent(jLabel40)
                    .addComponent(jLabel42))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel41)
                    .addComponent(jLabel30)
                    .addComponent(jLabel44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel43)
                    .addComponent(jLabel32)
                    .addComponent(jLabel46))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addContainerGap(52, Short.MAX_VALUE))
>>>>>>> origin/master
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DemographicInterface demographic = new DemographicInterface(session, this.patient,this.main);
        demographic.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JLabel BMI;
    private javax.swing.JLabel BMIData;
    private javax.swing.JLabel Birthday;
    private javax.swing.JLabel BloodPressureDiastolic;
    private javax.swing.JLabel BloodPressureDiastolicData;
    private javax.swing.JLabel BloodPressureSystolic;
    private javax.swing.JLabel BloodPressureSystolicData;
    private javax.swing.JLabel Contacts;
    private javax.swing.JLabel ContactsData;
    private javax.swing.JLabel Demographics;
    private javax.swing.JLabel Height;
    private javax.swing.JLabel HeightData;
    private javax.swing.JLabel Job;
    private javax.swing.JLabel MaritalStatus;
    private javax.swing.JLabel MostRecentVisitVitals;
    private javax.swing.JLabel OxygenSaturation;
    private javax.swing.JLabel OxygenSaturationData;
    private javax.swing.JLabel Phone;
    private javax.swing.JLabel PhoneData;
    private javax.swing.JLabel PlanName;
    private javax.swing.JLabel PlanNameData;
    private javax.swing.JLabel PolicyNumber;
    private javax.swing.JLabel PolicyNumberData;
    private javax.swing.JLabel Provider;
    private javax.swing.JLabel ProviderData;
    private javax.swing.JLabel Pulse;
    private javax.swing.JLabel PulseData;
    private javax.swing.JLabel Sex;
    private javax.swing.JLabel TemperatureC;
    private javax.swing.JLabel TemperatureData;
    private javax.swing.JLabel Weight;
    private javax.swing.JLabel WeightData;
=======
>>>>>>> origin/master
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
<<<<<<< HEAD
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel45;
=======
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
>>>>>>> origin/master
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
