package EHRAppointment;

import java.util.List;
import javax.swing.ImageIcon;

/**
 *
 * @author Austin, Olena, Daniel
 */
public class PreviousVitalsInterface extends javax.swing.JFrame {
    private static final long serialVersionUID = 1882994013566972940L;

    /**
     * Creates new form PreviousVitalsInterface
     */
    List<Vitals> result;

    /**
     *
     * @param result
     */
    public PreviousVitalsInterface(List<Vitals> result) {
        initComponents();
        this.result=result;
        updateCombo();
    }
    
    private void updateCombo(){         //Updating combo box to show dates of vitals
        jComboBox1.removeAllItems();
        for(Vitals vital :result){
            jComboBox1.addItem(vital);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        SelectDate = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        Name = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Weight = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BPSystolic = new javax.swing.JLabel();
        BPDiabolic = new javax.swing.JLabel();
        Pulse = new javax.swing.JLabel();
        Temperature = new javax.swing.JLabel();
        TempLocation = new javax.swing.JLabel();
        OxygenSaturation = new javax.swing.JLabel();
        BMI = new javax.swing.JLabel();
        WeightData = new javax.swing.JLabel();
        HeightData = new javax.swing.JLabel();
        BPSystolicData = new javax.swing.JLabel();
        BPDiabolicData = new javax.swing.JLabel();
        PulseData = new javax.swing.JLabel();
        TemperatureData = new javax.swing.JLabel();
        TempLocationData = new javax.swing.JLabel();
        OxygenSaturationData = new javax.swing.JLabel();
        BMIData = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setTitle("Patient Previous Vitals");
        setIconImage(new ImageIcon(getClass().getResource("/images/icon_transparent.png")).getImage());
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Previous Vitals");

        SelectDate.setText("Select date:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Name.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Value");

        Weight.setText("Weight");

        jLabel6.setText("Height");

        BPSystolic.setText("BP Systolic");

        BPDiabolic.setText("BP Diabolic");

        Pulse.setText("Pulse");

        Temperature.setText("Temperature");

        TempLocation.setText("Temp location");

        OxygenSaturation.setText("Oxygen saturation");

        BMI.setText("BMI");

        WeightData.setText("jLabel14");

        HeightData.setText("jLabel15");

        BPSystolicData.setText("jLabel16");

        BPDiabolicData.setText("jLabel17");

        PulseData.setText("jLabel18");

        TemperatureData.setText("jLabel19");

        TempLocationData.setText("jLabel20");

        OxygenSaturationData.setText("jLabel21");

        BMIData.setText("jLabel22");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/vitals icon.jpg"))); // NOI18N
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SelectDate)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Weight)
                            .addComponent(jLabel6)
                            .addComponent(BPSystolic)
                            .addComponent(BPDiabolic)
                            .addComponent(Pulse)
                            .addComponent(Temperature)
                            .addComponent(TempLocation)
                            .addComponent(BMI)
                            .addComponent(OxygenSaturation)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Name)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BMIData)
                            .addComponent(OxygenSaturationData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TempLocationData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TemperatureData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PulseData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BPDiabolicData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BPSystolicData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HeightData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(WeightData, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectDate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Weight)
                    .addComponent(WeightData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(HeightData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPSystolic)
                    .addComponent(BPSystolicData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BPDiabolic)
                    .addComponent(BPDiabolicData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pulse)
                    .addComponent(PulseData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Temperature)
                    .addComponent(TemperatureData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TempLocation)
                    .addComponent(TempLocationData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(OxygenSaturation)
                    .addComponent(OxygenSaturationData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BMI)
                    .addComponent(BMIData))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        //Selecting from combo box
        Vitals vital = (Vitals)jComboBox1.getSelectedItem();    //get selected item from combo box
        if(vital!=null){
        WeightData.setText(vital.getWeight()+"");                 //Showing the vital info
        HeightData.setText(vital.getHeight()+"");
        BPSystolicData.setText(vital.getBpSystolic()+"");
        BPDiabolicData.setText(vital.getBpDiastolic()+"");
        PulseData.setText(vital.getPulse()+"");
        TemperatureData.setText(vital.getTemperature()+"");
        TempLocationData.setText(vital.getTempLocation());
        OxygenSaturationData.setText(vital.getOxygenSaturation()+"");
        BMIData.setText(vital.getBmi()+"");
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PreviousVitalsInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                List<Vitals> l=null;
                new PreviousVitalsInterface(l).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BMI;
    private javax.swing.JLabel BMIData;
    private javax.swing.JLabel BPDiabolic;
    private javax.swing.JLabel BPDiabolicData;
    private javax.swing.JLabel BPSystolic;
    private javax.swing.JLabel BPSystolicData;
    private javax.swing.JLabel HeightData;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel OxygenSaturation;
    private javax.swing.JLabel OxygenSaturationData;
    private javax.swing.JLabel Pulse;
    private javax.swing.JLabel PulseData;
    private javax.swing.JLabel SelectDate;
    private javax.swing.JLabel TempLocation;
    private javax.swing.JLabel TempLocationData;
    private javax.swing.JLabel Temperature;
    private javax.swing.JLabel TemperatureData;
    private javax.swing.JLabel Weight;
    private javax.swing.JLabel WeightData;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
