package EHRAppointment;
    /**
     * Creates new form ScheduleInterface
     */
import EHRAppointment.Patient;
import EHRAppointment.Schedule;
import java.awt.HeadlessException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;
import org.hibernate.Session;
import org.jdesktop.swingx.JXDatePicker;
/**
 *
 * @author Austin, Olena, Daniel
 */
public class ScheduleInterface extends javax.swing.JPanel {
    private static final long serialVersionUID = 2049515531716213762L;

    Session session;
    Patient patient;
    JXDatePicker picker;                //Calander object
    SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");   //To test the date format
    private int tablePosition = -1;     //To track the table position

    public ScheduleInterface(Session session) {
        initComponents();

        this.session = session;

        picker = new JXDatePicker();            //Setting calender
        picker.setDate(Calendar.getInstance().getTime());
        picker.setFormats(new SimpleDateFormat("yyyy-MM-dd"));
        add(picker, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, -1, -1));

        updateComobo();             //Updating combo box to get locations currently available

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        SelectLocations = new javax.swing.JLabel();
        SelectLocationData = new javax.swing.JComboBox();
        OrEnter = new javax.swing.JLabel();
        OrEnterData = new javax.swing.JTextField();
        SelectStartTime = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        SelectStartTimeData = new javax.swing.JComboBox();
        SelectEndTime = new javax.swing.JLabel();
        SelectEndTimeData = new javax.swing.JComboBox();
        IncludeTimeInSearch = new javax.swing.JCheckBox();
        SearchSchedule = new javax.swing.JButton();
        SaveSchedule = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        IncludeLocationInSearch = new javax.swing.JCheckBox();
        AddEntry = new javax.swing.JButton();
        RemoveEntry = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Scheduling");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Age:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, -1, -1));

        jLabel4.setText("value");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Medical issue:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, -1, -1));

        jLabel6.setText("value");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, -1, -1));

        jSeparator2.setMinimumSize(new java.awt.Dimension(1060, 0));
        jSeparator2.setPreferredSize(new java.awt.Dimension(1060, 2));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 995, 10));

        SelectLocations.setText("Select location:");
        add(SelectLocations, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        SelectLocationData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectLocationData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectLocationDataActionPerformed(evt);
            }
        });
        add(SelectLocationData, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 90, -1));

        OrEnter.setText("or Enter:");
        add(OrEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));
        add(OrEnterData, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 90, -1));

        SelectStartTime.setText("Select start time:");
        add(SelectStartTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, -1, -1));

        jLabel10.setText("Select date:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        SelectStartTimeData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        add(SelectStartTimeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, -1, -1));

        SelectEndTime.setText("Select end time:");
        add(SelectEndTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        SelectEndTimeData.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "00", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        add(SelectEndTimeData, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 130, -1, -1));

        IncludeTimeInSearch.setText("Include time in seach");
        add(IncludeTimeInSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 130, -1, -1));

        SearchSchedule.setBackground(new java.awt.Color(153, 255, 153));
        SearchSchedule.setText("Search schedule");
        SearchSchedule.setToolTipText("Search saved schedules");
        SearchSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchScheduleActionPerformed(evt);
            }
        });
        add(SearchSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 100, -1, -1));

        SaveSchedule.setBackground(new java.awt.Color(153, 255, 153));
        SaveSchedule.setText("Save schedule");
        SaveSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveScheduleActionPerformed(evt);
            }
        });
        add(SaveSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 120, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Total number of patients scheduled:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 20, 10));

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Location", "Date", "Start time", "End tilme"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(3).setMinWidth(40);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(40);
            jTable1.getColumnModel().getColumn(4).setMinWidth(40);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(40);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 680, 160));

        IncludeLocationInSearch.setText("Include location in search");
        add(IncludeLocationInSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, -1, -1));

        AddEntry.setBackground(new java.awt.Color(153, 255, 153));
        AddEntry.setText("Add entry");
        AddEntry.setToolTipText("Add schedule to table");
        AddEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEntryActionPerformed(evt);
            }
        });
        add(AddEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 100, -1));

        RemoveEntry.setBackground(new java.awt.Color(255, 204, 204));
        RemoveEntry.setText("Remove entry");
        RemoveEntry.setToolTipText("Remove entry froom table");
        RemoveEntry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveEntryActionPerformed(evt);
            }
        });
        add(RemoveEntry, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scheduleEdt.jpg"))); // NOI18N
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 100, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void SelectLocationDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectLocationDataActionPerformed
        //Set location of the text area equal to selected location from combo box
        String sch = (String) SelectLocationData.getSelectedItem();
        if (sch != null) {
            this.OrEnterData.setText(sch);
        }

    }//GEN-LAST:event_SelectLocationDataActionPerformed

    private void SaveScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveScheduleActionPerformed
        //Add schedule to database
        Schedule sch = new Schedule();
        try {
            java.sql.Date sqlDate = null;
            java.util.Date invoiceDate = formatDate.parse(picker.getEditor().getText()); //get date from clander object
            sqlDate = new java.sql.Date(invoiceDate.getTime());

            sch.setDate(sqlDate);
            sch.setLocation(OrEnterData.getText());
            int start = Integer.parseInt(SelectStartTimeData.getSelectedItem().toString());      //get start and end time slots
            int end = Integer.parseInt(SelectEndTimeData.getSelectedItem().toString());
            sch.setStartTime(start);                //Set start and end time to schedule object
            sch.setEndTime(end);
            sch.setPatientId(patient.getPatientId());

            java.util.Date date = new java.util.Date(); //Check the scheduling date is after today
            if (date.after(sqlDate)) {
                JOptionPane.showMessageDialog(this, "Please use valid date", "Schedule", JOptionPane.INFORMATION_MESSAGE);

            } else if (start < end || (start == 12 && end == 13)) { //checking for clash

                session.beginTransaction();                                     //code1= start code2 =end
                Query qr = session.createQuery("from Schedule where ((startTime<= :code1 and :code1 <=endTime) or (startTime<= :code2 and :code2 <=endTime)) and (location!=:code3) and (date= :code4)");
                qr.setParameter("code1", start);
                qr.setParameter("code2", end);
                qr.setParameter("code3", OrEnterData.getText());
                qr.setParameter("code4", sqlDate);
                List<Schedule> result = qr.list();
                session.getTransaction().commit();

                if (result.isEmpty()) {
                    session.beginTransaction();
                    session.save(sch);                                  //Saving object 
                    session.getTransaction().commit();
                    JOptionPane.showMessageDialog(null, "Schedule saved successfully", "Schedules", JOptionPane.INFORMATION_MESSAGE);

                } else {
                    //Error message to overlap time clash in two location same time problem
                    JOptionPane.showMessageDialog(null, "Time clash", "Schedules", JOptionPane.WARNING_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(this, "Please use valid time slot", "Schedule", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (ParseException | NumberFormatException | HeadlessException e) {
            System.out.println("" + e.getMessage());
            JOptionPane.showMessageDialog(this, "Enter date in correct format", "Schedule", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_SaveScheduleActionPerformed

    private void AddEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEntryActionPerformed
        //Add schedule to table
        try {
            java.sql.Date sqlDate = null;
            java.util.Date invoiceDate = formatDate.parse(picker.getEditor().getText()); //geting date from 
            sqlDate = new java.sql.Date(invoiceDate.getTime());

            int start = Integer.parseInt(SelectStartTimeData.getSelectedItem().toString());  //get start and end time
            int end = Integer.parseInt(SelectEndTimeData.getSelectedItem().toString());

            java.util.Date date = new java.util.Date();
            if (date.after(sqlDate)) {                      //Checking date is after
                JOptionPane.showMessageDialog(this, "Please use valid date", "Schedule", JOptionPane.INFORMATION_MESSAGE);

            } else if (start < end || (start == 12 && end == 13)) {

                if (tablePosition == jTable1.getRowCount() - 1) {   //If rows are finished. Create new one
                    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                    model.addRow(new Object[]{null, null, null});
                }

                jTable1.setValueAt(patient.getName(), ++tablePosition, 0);
                jTable1.setValueAt(OrEnterData.getText(), tablePosition, 1);
                jTable1.setValueAt(picker.getEditor().getText(), tablePosition, 2);
                jTable1.setValueAt(start + ".00", tablePosition, 3);
                jTable1.setValueAt(end + ".00", tablePosition, 4);

            } else {
                JOptionPane.showMessageDialog(this, "Please use valid time slot", "Schedule", JOptionPane.INFORMATION_MESSAGE);
            }


        } catch (ParseException ex) {
            Logger.getLogger(ScheduleInterface.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_AddEntryActionPerformed

    private void RemoveEntryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveEntryActionPerformed
        //Removing item from table
        int selectedRow = this.jTable1.getSelectedRow();
        try {
            Schedule selected = (Schedule) jTable1.getValueAt(selectedRow, 1);

            int result;
            result = JOptionPane.showConfirmDialog(this, "You are going to remove previous schedule", "Schedule", JOptionPane.OK_CANCEL_OPTION);
            if (result == 0) {              //Ok message

                session.beginTransaction();
                session.delete(selected);
                session.getTransaction().commit();

                this.tablePosition--;           //Reduce table position from one
                DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
                int[] rows = jTable1.getSelectedRows();
                for (int i = 0; i < rows.length; i++) { //remove rows
                    model.removeRow(rows[i] - i);
                }
            }

        } catch (java.lang.ClassCastException e) {
            this.tablePosition--;
            DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
            int[] rows = jTable1.getSelectedRows();
            for (int i = 0; i < rows.length; i++) {
                model.removeRow(rows[i] - i);
            }
        }


    }//GEN-LAST:event_RemoveEntryActionPerformed

    private void SearchScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchScheduleActionPerformed
        //Searching schedules
        try {
            boolean location = IncludeLocationInSearch.isSelected(); //Checking for location and time search
            boolean time = IncludeTimeInSearch.isSelected();

            java.sql.Date sqlDate = null;
            java.util.Date invoiceDate = formatDate.parse(picker.getEditor().getText()); //get selected date
            sqlDate = new java.sql.Date(invoiceDate.getTime());

            session.beginTransaction();

            if (location && time) {  //Compare with check boxes and do required action
                Query qr = session.createQuery("from Schedule where date=:code1 and startTime=:code2 and endTime=:code3 and location=:code4");
                qr.setParameter("code1", sqlDate);
                qr.setParameter("code4", OrEnterData.getText());
                qr.setParameter("code2", Integer.parseInt(SelectStartTimeData.getSelectedItem().toString()));
                qr.setParameter("code3", Integer.parseInt(SelectEndTimeData.getSelectedItem().toString()));
                List<Schedule> result = qr.list();
                session.getTransaction().commit();
                addToTable(result);
                jLabel13.setText(result.size() + "");

            } else if (location && !time) {
                Query qr = session.createQuery("from Schedule where date=:code1 and location=:code4");
                qr.setParameter("code1", sqlDate);
                qr.setParameter("code4", OrEnterData.getText());
                List<Schedule> result = qr.list();
                session.getTransaction().commit();
                addToTable(result);
                jLabel13.setText(result.size() + "");

            } else if (!location && time) {
                Query qr = session.createQuery("from Schedule where date=:code1 and startTime=:code2 and endTime=:code3");
                qr.setParameter("code1", sqlDate);
                qr.setParameter("code2", Integer.parseInt(SelectStartTimeData.getSelectedItem().toString()));
                qr.setParameter("code3", Integer.parseInt(SelectEndTimeData.getSelectedItem().toString()));
                List<Schedule> result = qr.list();
                session.getTransaction().commit();
                addToTable(result);
                jLabel13.setText(result.size() + "");

            } else if (!location && !time) {
                Query qr = session.createQuery("from Schedule where date=:code1");
                qr.setParameter("code1", sqlDate);
                List<Schedule> result = qr.list();
                session.getTransaction().commit();
                addToTable(result);
                jLabel13.setText(result.size() + "");
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Enter date correctly", "Schedule", JOptionPane.WARNING_MESSAGE);
            Logger.getLogger(ScheduleInterface.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_SearchScheduleActionPerformed

    private void addToTable(List<Schedule> list) {  // Used to add search results to jtable
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        dtm.setNumRows(0);

        this.tablePosition = -1;
        for (Schedule sch : list) {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.addRow(new Object[]{null, null, null});

            session.beginTransaction();
            Query qr = session.createQuery("from Patient where patientId =:code");
            qr.setParameter("code", sch.getPatientId());
            List<Patient> result = qr.list();
            session.getTransaction().commit();

            jTable1.setValueAt(result.get(0).getName(), ++tablePosition, 0);
            jTable1.setValueAt(sch, tablePosition, 1);
            jTable1.setValueAt(sch.getDate().toString(), tablePosition, 2);
            jTable1.setValueAt(sch.getStartTime() + ".00", tablePosition, 3);
            jTable1.setValueAt(sch.getEndTime() + ".00", tablePosition, 4);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEntry;
    private javax.swing.JCheckBox IncludeLocationInSearch;
    private javax.swing.JCheckBox IncludeTimeInSearch;
    private javax.swing.JLabel OrEnter;
    private javax.swing.JTextField OrEnterData;
    private javax.swing.JButton RemoveEntry;
    private javax.swing.JButton SaveSchedule;
    private javax.swing.JButton SearchSchedule;
    private javax.swing.JLabel SelectEndTime;
    private javax.swing.JComboBox SelectEndTimeData;
    private javax.swing.JComboBox SelectLocationData;
    private javax.swing.JLabel SelectLocations;
    private javax.swing.JLabel SelectStartTime;
    private javax.swing.JComboBox SelectStartTimeData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    void updateInfo(Patient currentPatient) {       //Update all sub types of interfaces
        this.patient = currentPatient;
        updateDemographic();
        updateMedicalInfo();
        updateComobo();
    }

    private void updateDemographic() {              //Update dempgraphic information in interface
        jLabel2.setText(patient.getName());
        Calendar today = Calendar.getInstance();
        Calendar birthDate = Calendar.getInstance();
        birthDate.setTime(patient.getBirthday());
        int age = today.get(Calendar.YEAR) - birthDate.get(Calendar.YEAR);
        this.jLabel4.setText(age + "");
    }

    private void updateMedicalInfo() {   //Update medical info
        session.beginTransaction();
        Query qr = session.createQuery("from GeneralMedicalInfo where patientId =:code");
        qr.setParameter("code", patient.getPatientId());
        List<GeneralMedicalInfo> result = qr.list();
        session.getTransaction().commit();

        if (!result.isEmpty()) {
            GeneralMedicalInfo medical = result.get(0);
            this.jLabel6.setText(medical.getMainMedicalProblem());
        }
    }

    private void updateComobo() {   //Add locations to the combo box
        SelectLocationData.removeAllItems();

        session.beginTransaction();
        Query qr = session.createQuery("from Schedule group by location");
        List<Schedule> result = qr.list();
        session.getTransaction().commit();

        if (!result.isEmpty()) {
            for (Schedule sch : result) {
                SelectLocationData.addItem(sch.getLocation());
            }
        }

    }

}
